### ISSUE TITLE
Everything seemed to work fine, but emails are not going out.

### ISSUE THREAD

**Issue by CharlesPolk84** [siefkenj/MailMerge#20]
Sent to 100 addresses and noticed no replies or bounces. Added my name to a list, and email... it never came to my address.

Everything seems to be working just fine but its not. What am I missing? Thanks

**Comment by siefkenj** [comment]
If you check your Sent box, are the emails there? Also, can you let me know what version of TB you are using?

**Comment by papo1996** [comment]
I have the same issue, after clicking on send I get a loading popup for a second and then nothing happens. I tried a few times sending to my own personal emails to see if I would receive anything but it doesn't send emails. I am with the newest version of Thunderbird 91.3.0 (64 bit) please suggest what I can do to make it work since I have to send some emails and I really need it to work. Thank you !

**Comment by siefkenj** [comment]
That would explain it! I haven't tested with TB 91 yet. Hopefully I will be able to update MailMergeP to work with TB 91 over the winter holiday. Right now, it only works with TB 78,

**Comment by papo1996** [comment]
I have just installed the previous version and it works fine, thank you siefkenj, please write one comment here when you update the plugin so that I can update my Thunderbird to the newest one, thank you again for the amaizing plugin !
